/*
 *Made by Jordan Avelar
 *On December 10 2018
 *To help students study, and have fun, helpful breaks
*/
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.util.Random;
import javax.swing.Timer;
import javax.swing.JFrame;


public class TimerInterface extends javax.swing.JFrame {

    /**
     * Creates new form Timer
     */
    public TimerInterface() {
        initComponents();
        studyTimeInput.setText("30");
        breakTimeInput.setText("5");
        // Setting the default times for the timer
        
        Random rn = new Random();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timerScreen = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        remainingTimeOutput = new javax.swing.JTextField();
        remainingLabel = new javax.swing.JLabel();
        studyTimeInput = new javax.swing.JTextField();
        breakTimeInput = new javax.swing.JTextField();
        studyTimeLabel = new javax.swing.JLabel();
        breakTimeLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        pauseButton = new javax.swing.JButton();
        bookStackPNG = new javax.swing.JLabel();
        bookStackPNG1 = new javax.swing.JLabel();
        stopWatchPNG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        timerScreen.setBackground(new java.awt.Color(153, 204, 255));
        timerScreen.setMaximumSize(new java.awt.Dimension(575, 450));

        titleLabel.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 36)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Study Savvy");

        remainingTimeOutput.setEditable(false);
        remainingTimeOutput.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        remainingTimeOutput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        remainingTimeOutput.setAutoscrolls(false);

        remainingLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        remainingLabel.setText("Time Remaining");

        studyTimeInput.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        studyTimeInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        breakTimeInput.setEditable(false);
        breakTimeInput.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        breakTimeInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        studyTimeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studyTimeLabel.setText("Study Time (minutes)");

        breakTimeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        breakTimeLabel.setText("Break Time (minutes)");

        startButton.setText("Start Timer");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        pauseButton.setText("Stop Timer");
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });

        bookStackPNG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stack-of-Books.png"))); // NOI18N

        bookStackPNG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stack-of-Books.png"))); // NOI18N

        stopWatchPNG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stopWatchPNG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stop-Watch.png"))); // NOI18N

        javax.swing.GroupLayout timerScreenLayout = new javax.swing.GroupLayout(timerScreen);
        timerScreen.setLayout(timerScreenLayout);
        timerScreenLayout.setHorizontalGroup(
            timerScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timerScreenLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(studyTimeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(stopWatchPNG)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(breakTimeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timerScreenLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(studyTimeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(breakTimeLabel)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timerScreenLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(bookStackPNG, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(timerScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(timerScreenLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(titleLabel))
                    .addGroup(timerScreenLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(remainingLabel)))
                .addGap(18, 18, 18)
                .addComponent(bookStackPNG1)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(timerScreenLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(remainingTimeOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timerScreenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(startButton)
                .addGap(129, 129, 129)
                .addComponent(pauseButton)
                .addGap(136, 136, 136))
        );
        timerScreenLayout.setVerticalGroup(
            timerScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timerScreenLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(timerScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(timerScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(timerScreenLayout.createSequentialGroup()
                            .addComponent(titleLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(remainingLabel))
                        .addComponent(bookStackPNG1))
                    .addComponent(bookStackPNG, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(remainingTimeOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(timerScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(breakTimeLabel)
                    .addComponent(studyTimeLabel))
                .addGap(18, 18, 18)
                .addGroup(timerScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studyTimeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(breakTimeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stopWatchPNG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(timerScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(pauseButton))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timerScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timerScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        countdowntimer.stop();
    }//GEN-LAST:event_pauseButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        int study, Break, numbeeps = 10;
    
        study = Integer.parseInt(studyTimeInput.getText());
        Break = Integer.parseInt(breakTimeInput.getText());
        
        DecimalFormat x = new DecimalFormat ("00");
        
        second = 59;
        minute = study - 1;
        
        // The timer is set to update the count every 1000 milliseconds
        // which is every 1 second
        countdowntimer = new javax.swing.Timer(1000, new ActionListener() {
            
            public void actionPerformed(ActionEvent e) {
                
                // Here is the action that should be performed
                // after a specified time.
                
                remainingTimeOutput.setText(minute+":"+x.format(second));
                second = second - 1;
                
                // After the counter is less than 0 stop the counter.
                if (second == -1) {
                    second = 59;
                    minute = minute - 1;
                }
                if (minute == 0 && second == 0) {
                    countdowntimer.stop();
                    for(int x=0;x<numbeeps;x++){ // Plays a sound
                            java.awt.Toolkit.getDefaultToolkit().beep();
                    }   
                    // Choose a random game once more games are made
                    new Hangman().setVisible(true);
                    setVisible(false);
                }
                
            }
            
        });
        
        countdowntimer.start();
    }//GEN-LAST:event_startButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimerInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookStackPNG;
    private javax.swing.JLabel bookStackPNG1;
    private javax.swing.JTextField breakTimeInput;
    private javax.swing.JLabel breakTimeLabel;
    private javax.swing.JButton pauseButton;
    private javax.swing.JLabel remainingLabel;
    private javax.swing.JTextField remainingTimeOutput;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel stopWatchPNG;
    private javax.swing.JTextField studyTimeInput;
    private javax.swing.JLabel studyTimeLabel;
    private javax.swing.JPanel timerScreen;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
private int second, minute;
private Timer countdowntimer;
}
